default_platform(:ios)
#podspec_name = "Getpay-Core.podspec"

platform :ios do

  desc "Release a new version with a patch bump_type"
  lane :patch do
    release("patch")
  end

  desc "Release a new version with a minor bump_type"
  lane :minor do
    release("minor")
  end

  desc "Release a new version with a major bump_type"
  lane :major do
    release("major")
  end

  def release(type)
    #pod_lib_lint(allow_warnings: true)
    version = version_bump_podspec(path: "Getpay-Core.podspec",
                                   bump_type: type)
    git_add(path: "Getpay-Core.podspec")
    git_commit(path: ["Getpay-Core.podspec"],
               message: "#{version} upgrade repo")
    add_git_tag(tag: "#{version}")
    push_to_git_remote
    pod_push(repo: "Pods", allow_warnings: true)
  end
end